[package]
name = "expression"
version = "0.3.1"
authors = ["Michael Neumann <mneumann@ntecs.de>"]

license = "MIT"
repository = "https://github.com/mneumann/expression-rs"
description = "Implements expression terms and conditions"
keywords = ["expression", "term"]

[dependencies]
asexp = "0.1.0"
